// ============================================================
// backend/controllers/onboarding/termController.js
// SchoolBridge Enterprise
// Academic Term Controller
//
// RESPONSIBILITIES
// ------------------------------------------------------------
// - Handle HTTP requests for academic terms
// - Support onboarding Terms "Save & Continue"
// - Delegate business logic to termService.js
// - Maintain school-scoped security
// - Return consistent API responses
//
// CANONICAL TERM FIELDS
// ------------------------------------------------------------
// school
// academicSession
// name
// code
// termNumber
// position
// startDate
// endDate
// status
// isCurrent
// description
// isDeleted
// createdBy
// updatedBy
//
// IMPORTANT
// ------------------------------------------------------------
// Business logic belongs in:
// services/onboarding/termService.js
//
// This controller should NOT duplicate term validation,
// duplicate checking, current-term synchronization,
// onboarding progress logic, etc.
// ============================================================

import * as termService from "../../services/onboarding/termService.js";

// ============================================================
// RESPONSE HELPER
// ============================================================

const sendResponse = (
    res,
    statusCode,
    success,
    message,
    data = {}
) => {
    return res.status(statusCode).json({
        success,
        message,
        ...data,
    });
};

// ============================================================
// ERROR HELPER
// ============================================================
//
// Allows the controller to return a useful HTTP status while
// still allowing the global error middleware to handle errors
// when appropriate.
//
// ============================================================

const getErrorStatus = (error) => {
    if (!error) {
        return 500;
    }

    if (
        error.statusCode &&
        Number.isInteger(error.statusCode)
    ) {
        return error.statusCode;
    }

    if (
        error.status &&
        Number.isInteger(error.status)
    ) {
        return error.status;
    }

    // Validation / business-rule errors generated by
    // termService are normally client-side errors.
    const message =
        String(error.message || "").toLowerCase();

    const validationIndicators = [
        "required",
        "invalid",
        "duplicate",
        "already exists",
        "must be",
        "cannot be",
        "not found",
        "only",
        "term number",
        "academic session",
    ];

    if (
        validationIndicators.some(
            (item) =>
                message.includes(item)
        )
    ) {
        return 400;
    }

    return 500;
};

// ============================================================
// GET SCHOOL ID
// ============================================================
//
// schoolMiddleware should already have populated req.school.
// The fallback keeps compatibility with older middleware.
//
// ============================================================

const getSchoolId = (req) => {
    return (
        req.school?._id ||
        req.schoolId ||
        null
    );
};

// ============================================================
// GET USER ID
// ============================================================

const getUserId = (req) => {
    return (
        req.user?._id ||
        req.user?.id ||
        null
    );
};

// ============================================================
// SAVE TERMS - ONBOARDING
// ============================================================
//
// POST /api/school-setup/terms/setup
//
// Expected body:
//
// {
//   academicSession: "...",
//   terms: [
//     {
//       name: "First Term",
//       code: "FIRST",
//       termNumber: 1,
//       startDate: "...",
//       endDate: "...",
//       status: "Active",
//       isCurrent: true
//     },
//     ...
//   ]
// }
//
// This is the important endpoint for the onboarding wizard.
//
// It delegates to:
//
// termService.setupTerms()
//   -> createTerms()
//
// The service then:
// - validates the academic session
// - validates all terms
// - prevents duplicate configuration
// - creates terms
// - determines current term
// - synchronizes School.currentTerm
// - completes onboarding "terms"
// ============================================================

export const setupTerms = async (
    req,
    res,
    next
) => {
    try {
        const schoolId =
            getSchoolId(req);

        const userId =
            getUserId(req);

        if (!schoolId) {
            return sendResponse(
                res,
                400,
                false,
                "School context not found."
            );
        }

        const body =
            req.body || {};

        const academicSession =
            body.academicSession ||
            body.academicSessionId ||
            body.sessionId;

        const terms =
            body.terms ||
            body;

        if (!academicSession) {
            return sendResponse(
                res,
                400,
                false,
                "Academic session is required."
            );
        }

        if (!Array.isArray(terms)) {
            return sendResponse(
                res,
                400,
                false,
                "Terms must be provided as an array."
            );
        }

        const result =
            await termService.setupTerms(
                schoolId,
                academicSession,
                terms,
                {
                    userId,
                }
            );

        return sendResponse(
            res,
            201,
            true,
            "Terms saved successfully.",
            {
                terms:
                    result.terms,

                onboarding:
                    result.onboarding,
            }
        );
    } catch (error) {
        console.error(
            "Setup Terms Error:",
            error
        );

        return next(error);
    }
};

// ============================================================
// CREATE TERM
// ============================================================
//
// POST /api/school-setup/terms
//
// Creates one individual term.
//
// Used after onboarding or from the School Setup CRUD UI.
//
// ============================================================

export const createTerm = async (
    req,
    res,
    next
) => {
    try {
        const schoolId =
            getSchoolId(req);

        if (!schoolId) {
            return sendResponse(
                res,
                400,
                false,
                "School context not found."
            );
        }

        const userId =
            getUserId(req);

        const body =
            req.body || {};

        const academicSession =
            body.academicSession ||
            body.academicSessionId ||
            body.sessionId;

        if (!academicSession) {
            return sendResponse(
                res,
                400,
                false,
                "Academic session is required."
            );
        }

        const result =
            await termService.createTerm(
                schoolId,
                academicSession,
                body,
                {
                    userId,
                }
            );

        return sendResponse(
            res,
            201,
            true,
            "Term created successfully.",
            {
                term:
                    result.term,

                onboarding:
                    result.onboarding,
            }
        );
    } catch (error) {
        console.error(
            "Create Term Error:",
            error
        );

        return next(error);
    }
};

// ============================================================
// GET ALL TERMS
// ============================================================
//
// GET /api/school-setup/terms
//
// Query parameters:
//
// ?academicSession=<id>
// ?search=first
// ?page=1
// ?limit=20
//
// ============================================================

export const getTerms = async (
    req,
    res,
    next
) => {
    try {
        const schoolId =
            getSchoolId(req);

        if (!schoolId) {
            return sendResponse(
                res,
                400,
                false,
                "School context not found."
            );
        }

        const academicSession =
            req.query.academicSession ||
            req.query.academicSessionId ||
            req.query.sessionId ||
            null;

        const result =
            await termService.getTerms(
                schoolId,
                academicSession
            );

        return sendResponse(
            res,
            200,
            true,
            "Terms retrieved successfully.",
            {
                terms: result,
            }
        );
    } catch (error) {
        console.error(
            "Get Terms Error:",
            error
        );

        return next(error);
    }
};

// ============================================================
// GET SINGLE TERM
// ============================================================
//
// GET /api/school-setup/terms/:id
//
// ============================================================

export const getTerm = async (
    req,
    res,
    next
) => {
    try {
        const schoolId =
            getSchoolId(req);

        if (!schoolId) {
            return sendResponse(
                res,
                400,
                false,
                "School context not found."
            );
        }

        const {
            id,
        } = req.params;

        const term =
            await termService.getTerm(
                schoolId,
                id
            );

        return sendResponse(
            res,
            200,
            true,
            "Term retrieved successfully.",
            {
                term,
            }
        );
    } catch (error) {
        console.error(
            "Get Term Error:",
            error
        );

        return next(error);
    }
};

// ============================================================
// GET CURRENT TERM
// ============================================================
//
// GET /api/school-setup/terms/current
//
// IMPORTANT:
// The route MUST be registered before:
//
// /terms/:id
//
// Otherwise "current" can be interpreted as a term ID.
//
// ============================================================

export const getCurrentTerm = async (
    req,
    res,
    next
) => {
    try {
        const schoolId =
            getSchoolId(req);

        if (!schoolId) {
            return sendResponse(
                res,
                400,
                false,
                "School context not found."
            );
        }

        const term =
            await termService.getCurrentTerm(
                schoolId
            );

        return sendResponse(
            res,
            200,
            true,
            "Current term retrieved successfully.",
            {
                term,
            }
        );
    } catch (error) {
        console.error(
            "Get Current Term Error:",
            error
        );

        return next(error);
    }
};

// ============================================================
// UPDATE TERM
// ============================================================
//
// PUT /api/school-setup/terms/:id
//
// ============================================================

export const updateTerm = async (
    req,
    res,
    next
) => {
    try {
        const schoolId =
            getSchoolId(req);

        if (!schoolId) {
            return sendResponse(
                res,
                400,
                false,
                "School context not found."
            );
        }

        const userId =
            getUserId(req);

        const {
            id,
        } = req.params;

        const result =
            await termService.updateTerm(
                schoolId,
                id,
                req.body || {},
                {
                    userId,
                }
            );

        return sendResponse(
            res,
            200,
            true,
            "Term updated successfully.",
            {
                term:
                    result.term,

                onboarding:
                    result.onboarding,
            }
        );
    } catch (error) {
        console.error(
            "Update Term Error:",
            error
        );

        return next(error);
    }
};

// ============================================================
// DELETE TERM
// ============================================================
//
// DELETE /api/school-setup/terms/:id
//
// Soft delete is handled by termService.
//
// ============================================================

export const deleteTerm = async (
    req,
    res,
    next
) => {
    try {
        const schoolId =
            getSchoolId(req);

        if (!schoolId) {
            return sendResponse(
                res,
                400,
                false,
                "School context not found."
            );
        }

        const userId =
            getUserId(req);

        const {
            id,
        } = req.params;

        const result =
            await termService.deleteTerm(
                schoolId,
                id,
                {
                    userId,
                }
            );

        return sendResponse(
            res,
            200,
            true,
            "Term deleted successfully.",
            {
                term:
                    result.term,

                onboarding:
                    result.onboarding,
            }
        );
    } catch (error) {
        console.error(
            "Delete Term Error:",
            error
        );

        return next(error);
    }
};

// ============================================================
// SET CURRENT TERM
// ============================================================
//
// POST /api/school-setup/terms/:id/current
//
// ============================================================

export const setCurrentTerm = async (
    req,
    res,
    next
) => {
    try {
        const schoolId =
            getSchoolId(req);

        if (!schoolId) {
            return sendResponse(
                res,
                400,
                false,
                "School context not found."
            );
        }

        const userId =
            getUserId(req);

        const {
            id,
        } = req.params;

        const term =
            await termService.setCurrentTerm(
                schoolId,
                id,
                {
                    userId,
                }
            );

        return sendResponse(
            res,
            200,
            true,
            "Current term updated successfully.",
            {
                term,
            }
        );
    } catch (error) {
        console.error(
            "Set Current Term Error:",
            error
        );

        return next(error);
    }
};

// ============================================================
// UPDATE COMPLETE TERMS CONFIGURATION
// ============================================================
//
// PUT /api/school-setup/terms/setup
//
// This is useful when the onboarding Terms page already has
// existing terms and the user presses:
//
// "Save & Continue"
//
// Unlike createTerm(), this updates the complete configuration
// while preserving existing Term IDs.
//
// ============================================================

export const updateTerms = async (
    req,
    res,
    next
) => {
    try {
        const schoolId =
            getSchoolId(req);

        if (!schoolId) {
            return sendResponse(
                res,
                400,
                false,
                "School context not found."
            );
        }

        const userId =
            getUserId(req);

        const body =
            req.body || {};

        const academicSession =
            body.academicSession ||
            body.academicSessionId ||
            body.sessionId;

        const terms =
            body.terms;

        if (!academicSession) {
            return sendResponse(
                res,
                400,
                false,
                "Academic session is required."
            );
        }

        if (!Array.isArray(terms)) {
            return sendResponse(
                res,
                400,
                false,
                "Terms must be provided as an array."
            );
        }

        const result =
            await termService.updateTerms(
                schoolId,
                academicSession,
                terms,
                {
                    userId,
                }
            );

        return sendResponse(
            res,
            200,
            true,
            "Terms updated successfully.",
            {
                terms:
                    result.terms,

                onboarding:
                    result.onboarding,
            }
        );
    } catch (error) {
        console.error(
            "Update Terms Error:",
            error
        );

        return next(error);
    }
};

// ============================================================
// DEFAULT EXPORT
// ============================================================

export default {
    setupTerms,
    createTerm,
    getTerms,
    getTerm,
    getCurrentTerm,
    updateTerm,
    updateTerms,
    deleteTerm,
    setCurrentTerm,
};